#!/usr/bin/env python3
"""Generate Lean conformance checks from canonical PSL compiler output.

This is deliberately a finite corpus bridge, not a universal proof that the
Python compiler implements the Lean semantics for every possible source.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src" / "utils"))

from paninian_compiler import PaninianFormalCompiler

CANONICAL_PROGRAMS = (
    "lopa_core.pvm",
    "sandhi_core.pvm",
    "paribhasha_valid_core.pvm",
    "key_lifecycle.pvm",
    "anuvritti_core.pvm",
    "adhikara_core.pvm",
    "boot_sequencer.pvm",
    "safety_interlock.pvm",
)


def lean_nat_list(words):
    return "[" + ", ".join(f"0x{w:08X}" for w in words) + "]"


def main():
    output = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "lean" / "GeneratedConformance.lean"

    lines = [
        "import PSL.Semantics",
        "",
        "/-",
        "  AUTO-GENERATED by scripts/generate_lean_conformance.py.",
        "  Do not treat these finite examples as a universal compiler-correctness proof.",
        "-/",
        "",
    ]

    compiler = PaninianFormalCompiler()
    all_words = set()

    for name in CANONICAL_PROGRAMS:
        source = (ROOT / "programs" / name).read_text(encoding="utf-8")
        words = compiler.compile_source(source)
        all_words.update(words)
        theorem_name = "compiler_output_" + name.replace(".pvm", "").replace("-", "_")
        lines.extend(
            [
                f"-- {name}",
                f"example : validateEncodedClosed {lean_nat_list(words)} = true := by",
                "  native_decide",
                "",
            ]
        )

    for word in sorted(all_words):
        lines.extend(
            [
                f"example : ABIWord.toNat (decodeABIWord 0x{word:08X}) = 0x{word:08X} := by",
                "  native_decide",
                "",
            ]
        )

    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"generated {output} for {len(CANONICAL_PROGRAMS)} canonical PSL programs")


if __name__ == "__main__":
    main()
